/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author robert.talabishka
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Цена продажи");

        jLabel2.setText("Цена покупки");

        jLabel4.setText("Упущенная выгода");

        jTextField1.setText("75");
        jTextField1.setPreferredSize(new java.awt.Dimension(60, 25));

        jTextField2.setText("40");
        jTextField2.setPreferredSize(new java.awt.Dimension(60, 25));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("50");
        jTextField3.setPreferredSize(new java.awt.Dimension(60, 25));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(0),  new Double(0.0),  new Double(-50.0),  new Double(-100.0),  new Double(-150.0), null, null, null, null},
                { new Integer(1),  new Double(-40.0),  new Double(35.0),  new Double(-15.0),  new Double(-65.0), null, null, null, null},
                { new Integer(2),  new Double(-80.0),  new Double(-5.0),  new Double(70.0),  new Double(20.0), null, null, null, null},
                { new Integer(3),  new Double(-120.0),  new Double(-45.0),  new Double(30.0),  new Double(105.0), null, null, null, null}
            },
            new String [] {
                "Решение", "0", "1", "2", "3", "Ожидаемы платеж", "Минимальный доход", "Максимальный доход", "Критерий"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(80);
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(2).setMinWidth(50);
            jTable1.getColumnModel().getColumn(3).setMinWidth(50);
            jTable1.getColumnModel().getColumn(4).setMinWidth(50);
            jTable1.getColumnModel().getColumn(5).setMinWidth(150);
            jTable1.getColumnModel().getColumn(6).setMinWidth(150);
            jTable1.getColumnModel().getColumn(7).setMinWidth(170);
            jTable1.getColumnModel().getColumn(8).setMinWidth(100);
        }

        jLabel5.setText("Состояние природы");

        jLabel6.setText("Вероятности");

        jTextField4.setText("0,25");

        jTextField5.setText("0,25");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setText("0,25");

        jTextField7.setText("0,25");

        jLabel7.setText("а=");

        jTextField8.setText("0.5");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel8.setText("Лапласа");

        jLabel9.setText("Max(Min)");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", null, null, null, null, null},
                {"1", null, null, null, null, null},
                {"2", null, null, null, null, null},
                {"3", null, null, null, null, null}
            },
            new String [] {
                "Решение", "0", "1", "2", "3", "Максимум потерь"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(80);
            jTable2.getColumnModel().getColumn(1).setMinWidth(50);
            jTable2.getColumnModel().getColumn(2).setMinWidth(50);
            jTable2.getColumnModel().getColumn(3).setMinWidth(50);
            jTable2.getColumnModel().getColumn(4).setMinWidth(50);
        }

        jLabel10.setText("Матрица сожаления");

        jLabel11.setText("Сэвиджа");

        jLabel12.setText("Гурвица");

        jButton1.setText("Расчет");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(418, 418, 418)
                                .addComponent(jLabel11))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel5)
                                        .addGap(107, 107, 107)
                                        .addComponent(jLabel8)
                                        .addGap(113, 113, 113)
                                        .addComponent(jLabel9)))
                                .addGap(255, 255, 255)
                                .addComponent(jLabel12)))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    public void result() {
        double at = Double.parseDouble(jTextField8.getText());
        double a = Double.parseDouble(jTextField1.getText());
        double b = Double.parseDouble(jTextField2.getText());
        double c = Double.parseDouble(jTextField3.getText());

        double a1 = (double) jTable1.getValueAt(0, 1);
        double a2 = (double) jTable1.getValueAt(0, 2);
        double a3 = (double) jTable1.getValueAt(0, 3);
        double a4 = (double) jTable1.getValueAt(0, 4);
        double[] mas1 = {a1, a2, a3, a4};

        double min1 = mas1[0];
        double max1 = mas1[0];
        for (int i = 1; i < mas1.length; i++) {

            if (min1 > mas1[i]) {
                min1 = mas1[i];

            }
            if (max1 < mas1[i]) {
                max1 = mas1[i];

            }

        }
        jTable1.setValueAt(min1, 0, 6);
        jTable1.setValueAt(max1, 0, 7);

        double b1 = (double) jTable1.getValueAt(1, 1);
        double b2 = (double) jTable1.getValueAt(1, 2);
        double b3 = (double) jTable1.getValueAt(1, 3);
        double b4 = (double) jTable1.getValueAt(1, 4);
        double[] mas2 = {b1, b2, b3, b4};

        double min2 = mas2[0];
        double max2 = mas1[0];
        for (int i = 1; i < mas2.length; i++) {

            if (min2 > mas2[i]) {
                min2 = mas2[i];

            }
            if (max2 < mas2[i]) {
                max2 = mas2[i];

            }

        }
        jTable1.setValueAt(min2, 1, 6);
        jTable1.setValueAt(max2, 1, 7);

        double c1 = (double) jTable1.getValueAt(2, 1);
        double c2 = (double) jTable1.getValueAt(2, 2);
        double c3 = (double) jTable1.getValueAt(2, 3);
        double c4 = (double) jTable1.getValueAt(2, 4);
        double[] mas3 = {c1, c2, c3, c4};

        double min3 = mas3[0];
        double max3 = mas1[0];
        for (int i = 1; i < mas3.length; i++) {

            if (min3 > mas3[i]) {
                min3 = mas3[i];

            }
            if (max3 < mas3[i]) {
                max3 = mas3[i];

            }

        }
        jTable1.setValueAt(min3, 2, 6);
        jTable1.setValueAt(max3, 2, 7);

        double d1 = (double) jTable1.getValueAt(3, 1);
        double d2 = (double) jTable1.getValueAt(3, 2);
        double d3 = (double) jTable1.getValueAt(3, 3);
        double d4 = (double) jTable1.getValueAt(3, 4);
        double[] mas4 = {d1, d2, d3, d4};

        double min4 = mas4[0];
        double max4 = mas1[0];
        for (int i = 1; i < mas4.length; i++) {

            if (min4 > mas4[i]) {
                min4 = mas4[i];

            }
            if (max4 < mas4[i]) {
                max4 = mas4[i];

            }

        }
        jTable1.setValueAt(min4, 3, 6);
        jTable1.setValueAt(max4, 3, 7);

        double op1 = (a1 + a2 + a3 + a4) / 4;
        double op2 = (b1 + b2 + b3 + b4) / 4;
        double op3 = (c1 + c2 + c3 + c4) / 4;
        double op4 = (d1 + d2 + d3 + d4) / 4;

        jTable1.setValueAt(op1, 0, 5);
        jTable1.setValueAt(op2, 1, 5);
        jTable1.setValueAt(op3, 2, 5);
        jTable1.setValueAt(op4, 3, 5);

        double k1 = at * max1 + (1 - at) * min1;
        double k2 = at * max2 + (1 - at) * min2;
        double k3 = at * max3 + (1 - at) * min3;
        double k4 = at * max4 + (1 - at) * min4;

        jTable1.setValueAt(k1, 0, 8);
        jTable1.setValueAt(k2, 1, 8);
        jTable1.setValueAt(k3, 2, 8);
        jTable1.setValueAt(k4, 3, 8);

        double[] arr1 = {a1, b1, c1, d1};
        double mx1 = arr1[0];
        for (int i = 1; i < arr1.length; i++) {
            if (mx1 < arr1[i]) {
                mx1 = arr1[i];
            }
        }
        double[] arr2 = {a2, b2, c2, d2};
        double mx2 = arr2[0];
        for (int i = 1; i < arr2.length; i++) {
            if (mx2 < arr2[i]) {
                mx2 = arr2[i];
            }
        }
        double[] arr3 = {a3, b3, c3, d3};
        double mx3 = arr3[0];
        for (int i = 1; i < arr3.length; i++) {
            if (mx3 < arr3[i]) {
                mx3 = arr3[i];
            }
        }
        double[] arr4 = {a4, b4, c4, d4};
        double mx4 = arr4[0];
        for (int i = 1; i < arr4.length; i++) {
            if (mx4 < arr4[i]) {
                mx4 = arr4[i];
            }
        }
       jTable2.setValueAt(mx1-a1, 0, 1);
       jTable2.setValueAt(mx1-b1, 1, 1);
       jTable2.setValueAt(mx1-c1, 2, 1);
       jTable2.setValueAt(mx1-d1, 3, 1);
       jTable2.setValueAt(mx2-a2, 0, 2);
       jTable2.setValueAt(mx2-b2, 1, 2);
       jTable2.setValueAt(mx2-c2, 2, 2);
       jTable2.setValueAt(mx2-d2, 3, 2);
       jTable2.setValueAt(mx3-a3, 0, 3);
       jTable2.setValueAt(mx3-b3, 1, 3);
       jTable2.setValueAt(mx3-c3, 2, 3);
       jTable2.setValueAt(mx3-d3, 3, 3);
       jTable2.setValueAt(mx4-a4, 0, 4);
       jTable2.setValueAt(mx4-b4, 1, 4);
       jTable2.setValueAt(mx4-c4, 2, 4);
       jTable2.setValueAt(mx4-d4, 3, 4);
        
       double[] arr5 = {mx1-a1, mx2-a2, mx3-a3, mx4-a4};
       double[] arr6 = {mx1-b1, mx2-b2, mx3-b3, mx4-b4};
       double[] arr7 = {mx1-c1, mx2-c2, mx3-c3, mx4-c4};
       double[] arr8 = {mx1-d1, mx2-d2, mx3-d3, mx4-d4};
       
        double m5 = arr5[0];
        double m6 = arr6[0];
        double m7 = arr7[0];
        double m8 = arr8[0];
        for (int i = 1; i < arr4.length; i++) {
            if (m5 < arr5[i]) {
                m5 = arr5[i]; 
            }
            if (m6 < arr6[i]) {
                m6 = arr6[i];
            }
            if (m7 < arr7[i]) {
                m7 = arr7[i];
            }
            if (m8 < arr8[i]) {
                m8 = arr8[i];
            }
            
        }
         jTable2.setValueAt(m5, 0, 5);
         jTable2.setValueAt(m6, 1, 5);
         jTable2.setValueAt(m7, 2, 5);
         jTable2.setValueAt(m8, 3, 5);
        

     {
            
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        result();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
