/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author robert.talabishka
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A1",  new Double(-1.0),  new Double(9.0),  new Double(6.0),  new Double(8.0), null},
                {"A2",  new Double(-2.0),  new Double(10.0),  new Double(4.0),  new Double(6.0), null},
                {"A3",  new Double(5.0),  new Double(3.0),  new Double(0.0),  new Double(7.0), null},
                {"A4",  new Double(7.0),  new Double(-2.0),  new Double(8.0),  new Double(4.0), null},
                {"bi", null, null, null, null, null}
            },
            new String [] {
                "", "B1", "B2", "B3", "B4", "ai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Вариант решения участника А:");

        jLabel2.setText("Вариант решения участника В:");

        jTextField1.setPreferredSize(new java.awt.Dimension(60, 25));

        jTextField2.setPreferredSize(new java.awt.Dimension(60, 25));

        jButton1.setText("Расчет");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   public void result() {
        
        double a1 = (double) jTable1.getValueAt(0, 1);
        double a2 = (double) jTable1.getValueAt(0, 2);
        double a3 = (double) jTable1.getValueAt(0, 3);
        double a4 = (double) jTable1.getValueAt(0, 4);
        double[] mas1 = {a1, a2, a3, a4};

        double min1 = mas1[0];
       
        for (int i = 1; i < mas1.length; i++) {
            if (min1 > mas1[i]) {
                min1 = mas1[i];
            }            
        }        
        double b1 = (double) jTable1.getValueAt(1, 1);
        double b2 = (double) jTable1.getValueAt(1, 2);
        double b3 = (double) jTable1.getValueAt(1, 3);
        double b4 = (double) jTable1.getValueAt(1, 4);
        double[] mas2 = {b1, b2, b3, b4};

        double min2 = mas2[0];

        for (int i = 1; i < mas2.length; i++) {
            if (min2 > mas2[i]) {
                min2 = mas2[i];
            }
        }
        double c1 = (double) jTable1.getValueAt(2, 1);
        double c2 = (double) jTable1.getValueAt(2, 2);
        double c3 = (double) jTable1.getValueAt(2, 3);
        double c4 = (double) jTable1.getValueAt(2, 4);
        double[] mas3 = {c1, c2, c3, c4};

        double min3 = mas3[0];
        for (int i = 1; i < mas3.length; i++) {
            if (min3 > mas3[i]) {
                min3 = mas3[i];
            }
        }        
        double d1 = (double) jTable1.getValueAt(3, 1);
        double d2 = (double) jTable1.getValueAt(3, 2);
        double d3 = (double) jTable1.getValueAt(3, 3);
        double d4 = (double) jTable1.getValueAt(3, 4);
        double[] mas4 = {d1, d2, d3, d4};

        double min4 = mas4[0];
        for (int i = 1; i < mas4.length; i++) {
            if (min4 > mas4[i]) {
                min4 = mas4[i];
            }           
        } 
        
        jTable1.setValueAt(min1, 4, 1);
        jTable1.setValueAt(min2, 4, 2);
        jTable1.setValueAt(min3, 4, 3);
        jTable1.setValueAt(min4, 4, 4);
        
        
        
        double[] arr1 = {a1, b1, c1, d1};
        double mx1 = arr1[0];
        for (int i = 1; i < arr1.length; i++) {
            if (mx1 > arr1[i]) {
                mx1 = arr1[i];
            }
        }
        double[] arr2 = {a2, b2, c2, d2};
        double mx2 = arr2[0];
        for (int i = 1; i < arr2.length; i++) {
            if (mx2 > arr2[i]) {
                mx2 = arr2[i];
            }
        }
        double[] arr3 = {a3, b3, c3, d3};
        double mx3 = arr3[0];
        for (int i = 1; i < arr3.length; i++) {
            if (mx3 > arr3[i]) {
                mx3 = arr3[i];
            }
        }
        double[] arr4 = {a4, b4, c4, d4};
        double mx4 = arr4[0];
        for (int i = 1; i < arr4.length; i++) {
            if (mx4 > arr4[i]) {
                mx4 = arr4[i];
            }
        }
        jTable1.setValueAt(mx1, 0, 5);
        jTable1.setValueAt(mx2, 1, 5);
        jTable1.setValueAt(mx3, 2, 5);
        jTable1.setValueAt(mx4, 3, 5);
        
        
        
       double[] bi={min1,min2,min3,min4};
       double bi1 = bi[0];
        for (int i = 1; i < bi.length; i++) {
            if (bi1 < bi[i]) {
                bi1 = bi[i];
            }
        }
        jTextField2.setText(String.format("%.4f", bi1));
       double[] ai={mx1,mx2,mx3,mx4};
       double ai1 = ai[0];
        for (int i = 1; i < ai.length; i++) {
            if (ai1 < ai[i]) {
                ai1 = ai[i];
            }
        }
        jTextField1.setText(String.format("%.4f", ai1));
   

     
            
        }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        result();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
